/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tracks */
        get: operations["list_tracks_api_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Track */
        get: operations["get_track_api_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Track
         * @description Creates a DRAFT ChangeSet from the given field edits — never
         *     writes directly (docs/PLAN.md §10).
         */
        patch: operations["patch_track_api_tracks__track_id__patch"];
        trace?: never;
    };
    "/api/changesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Changesets */
        get: operations["list_changesets_api_changesets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changesets/{change_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Changeset */
        get: operations["get_changeset_api_changesets__change_set_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changesets/{change_set_id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Changes */
        patch: operations["patch_changes_api_changesets__change_set_id__changes_patch"];
        trace?: never;
    };
    "/api/changesets/{change_set_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Changeset */
        post: operations["apply_changeset_api_changesets__change_set_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changesets/{change_set_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Changeset */
        post: operations["undo_changeset_api_changesets__change_set_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/bulk-edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Edit Tracks */
        post: operations["bulk_edit_tracks_api_tracks_bulk_edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/find-replace/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Find Replace */
        post: operations["preview_find_replace_api_tracks_find_replace_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/find-replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Find Replace */
        post: operations["apply_find_replace_api_tracks_find_replace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/strip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Strip Tracks */
        post: operations["strip_tracks_api_tracks_strip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Group */
        get: operations["get_group_api_groups__group_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/cascade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Cascade */
        post: operations["run_cascade_api_groups_cascade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Groups */
        post: operations["merge_groups_api_groups__group_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Split Group */
        post: operations["split_group_api_groups__group_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/reassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reassign Track */
        post: operations["reassign_track_api_groups__group_id__reassign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/force-singleton": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force To Singleton */
        post: operations["force_to_singleton_api_groups_force_singleton_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin Group */
        post: operations["pin_group_api_groups__group_id__pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fields */
        get: operations["list_fields_api_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Group Candidates */
        get: operations["get_group_candidates_api_groups__group_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage Group */
        post: operations["stage_group_api_groups__group_id__stage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Track Candidates */
        get: operations["get_track_candidates_api_tracks__track_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage Track */
        post: operations["stage_track_api_tracks__track_id__stage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paths/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Paths */
        post: operations["preview_paths_api_paths_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paths/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename Paths */
        post: operations["rename_paths_api_paths_rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_api_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Import */
        post: operations["start_import_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{import_session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import */
        get: operations["get_import_api_imports__import_session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{import_session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Import */
        post: operations["resume_import_api_imports__import_session_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich/replaygain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich Replaygain */
        post: operations["enrich_replaygain_api_enrich_replaygain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich/art": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich Art */
        post: operations["enrich_art_api_enrich_art_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrich/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich Lyrics */
        post: operations["enrich_lyrics_api_enrich_lyrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Duplicates */
        get: operations["list_duplicates_api_duplicates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/duplicates/{group_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Duplicate */
        post: operations["dismiss_duplicate_api_duplicates__group_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/duplicates/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect Duplicates */
        post: operations["detect_duplicates_api_duplicates_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blobs/{blob_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blob */
        get: operations["get_blob_api_blobs__blob_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spa Catch All */
        get: operations["spa_catch_all__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyDecisionsRequest */
        ApplyDecisionsRequest: {
            /** Decisions */
            decisions: components["schemas"]["ChangeDecisionIn"][];
        };
        /**
         * ApplyRequest
         * @description POST /changesets/{id}/apply body — entirely optional (docs/PLAN.md
         *     §11b): omitted or `backup: null` uses the configured apply.backup
         *     default rather than forcing a value.
         */
        ApplyRequest: {
            /** Backup */
            backup?: boolean | null;
        };
        /** AuthStatusOut */
        AuthStatusOut: {
            /** Enabled */
            enabled: boolean;
            /** Authenticated */
            authenticated: boolean;
        };
        /** BinaryDiffOut */
        BinaryDiffOut: {
            /** Old Summary */
            old_summary: string | null;
            /** New Summary */
            new_summary: string | null;
            /** Old Blob Id */
            old_blob_id: number | null;
            /** New Blob Id */
            new_blob_id: number | null;
        };
        /** BulkEditFieldIn */
        BulkEditFieldIn: {
            /** Field */
            field: string;
            /** New Value */
            new_value: unknown;
        };
        /** BulkEditRequest */
        BulkEditRequest: {
            /** Track Ids */
            track_ids: number[];
            /** Fields */
            fields: components["schemas"]["BulkEditFieldIn"][];
        };
        /** CandidateRowOut */
        CandidateRowOut: {
            /** Source */
            source: string;
            /** Ref Id */
            ref_id: string;
            /** Album */
            album: string | null;
            /** Album Artist */
            album_artist: string | null;
            /** Year */
            year: number | null;
            /** Label */
            label: string | null;
            /** Catalog Number */
            catalog_number: string | null;
            /** Track Count */
            track_count: number;
            /** Distance */
            distance: number;
            /** Adjusted Distance */
            adjusted_distance: number;
            /** Is Duplicate Of */
            is_duplicate_of: number[];
            /** Corroborated By */
            corroborated_by: string[];
        };
        /** ChangeDecisionIn */
        ChangeDecisionIn: {
            /** Change Id */
            change_id: number;
            /**
             * Decision
             * @enum {string}
             */
            decision: "pending" | "accepted" | "rejected";
            /** New Value */
            new_value?: unknown | null;
        };
        /** ChangeOut */
        ChangeOut: {
            /** Id */
            id: number;
            /** Seq */
            seq: number;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: number;
            /** Field */
            field: string;
            /** Op */
            op: string;
            /** Old Value */
            old_value: unknown;
            /** New Value */
            new_value: unknown;
            /** Confidence */
            confidence: number | null;
            /** Severity */
            severity: string;
            /** Decision */
            decision: string;
            /** Apply State */
            apply_state: string;
            /** Is Manual */
            is_manual: boolean;
            diff: components["schemas"]["FieldDiffOut"];
        };
        /** ChangeSetDetailOut */
        ChangeSetDetailOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Source */
            source: string;
            /** State */
            state: string;
            /** Scope Type */
            scope_type: string;
            /** Scope Id */
            scope_id: number | null;
            /** Created By */
            created_by: string;
            /** Candidate Source */
            candidate_source: string | null;
            /** Candidate Ref */
            candidate_ref: string | null;
            /** Undo Of Id */
            undo_of_id: number | null;
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /** Error */
            error: string | null;
            /** Changes */
            changes: components["schemas"]["ChangeOut"][];
        };
        /** ChangeSetPageOut */
        ChangeSetPageOut: {
            /** Items */
            items: components["schemas"]["ChangeSetSummaryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /** ChangeSetSummaryOut */
        ChangeSetSummaryOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Source */
            source: string;
            /** State */
            state: string;
            /** Scope Type */
            scope_type: string;
            /** Scope Id */
            scope_id: number | null;
            /** Created By */
            created_by: string;
            /** Candidate Source */
            candidate_source: string | null;
            /** Candidate Ref */
            candidate_ref: string | null;
            /** Undo Of Id */
            undo_of_id: number | null;
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /** Error */
            error: string | null;
        };
        /** DuplicateGroupListOut */
        DuplicateGroupListOut: {
            /** Items */
            items: components["schemas"]["DuplicateGroupOut"][];
        };
        /** DuplicateGroupOut */
        DuplicateGroupOut: {
            /** Id */
            id: number;
            /** Mb Recording Id */
            mb_recording_id: string;
            /** Basis */
            basis: string;
            /** Dismissed */
            dismissed: boolean;
            /** Tracks */
            tracks: components["schemas"]["DuplicateTrackOut"][];
        };
        /** DuplicateTrackOut */
        DuplicateTrackOut: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Title */
            title: string | null;
            /** Artist */
            artist: string | null;
            /** Format */
            format: string | null;
            /** Bitrate */
            bitrate: number | null;
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** FieldDiffOut */
        FieldDiffOut: {
            /** Field */
            field: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "multi_text" | "binary" | "scalar";
            /** Old Value */
            old_value: unknown;
            /** New Value */
            new_value: unknown;
            /**
             * Severity
             * @enum {string}
             */
            severity: "normal" | "destructive";
            /**
             * Old Spans
             * @default []
             */
            old_spans: components["schemas"]["InlineSpanOut"][];
            /**
             * New Spans
             * @default []
             */
            new_spans: components["schemas"]["InlineSpanOut"][];
            multi?: components["schemas"]["MultiValueDiffOut"] | null;
            binary?: components["schemas"]["BinaryDiffOut"] | null;
        };
        /** FieldInfoOut */
        FieldInfoOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /** Editable */
            editable: boolean;
            /** Multi Valued */
            multi_valued: boolean;
            /** Default Strip */
            default_strip: boolean;
        };
        /** FieldListOut */
        FieldListOut: {
            /** Items */
            items: components["schemas"]["FieldInfoOut"][];
        };
        /** FindReplacePreviewOut */
        FindReplacePreviewOut: {
            /** Rows */
            rows: components["schemas"]["FindReplacePreviewRowOut"][];
        };
        /** FindReplacePreviewRowOut */
        FindReplacePreviewRowOut: {
            /** Track Id */
            track_id: number;
            /** Old Value */
            old_value: string;
            /** New Value */
            new_value: string;
        };
        /** FindReplaceRequest */
        FindReplaceRequest: {
            /** Track Ids */
            track_ids: number[];
            /** Field */
            field: string;
            /** Find */
            find: string;
            /** Replace */
            replace: string;
            /**
             * Use Regex
             * @default false
             */
            use_regex: boolean;
        };
        /** ForceSingletonRequest */
        ForceSingletonRequest: {
            /** Track Id */
            track_id: number;
        };
        /** GroupDetailOut */
        GroupDetailOut: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Grouping Basis */
            grouping_basis: string | null;
            /** Grouping Confidence */
            grouping_confidence: number | null;
            /** Is Pinned */
            is_pinned: boolean;
            /** Album */
            album: string | null;
            /** Album Artist */
            album_artist: string | null;
            /** Year */
            year: number | null;
            /** Track Count */
            track_count: number;
            /** Expected Track Count */
            expected_track_count: number | null;
            /** Match State */
            match_state: string;
            /** Track Ids */
            track_ids: number[];
        };
        /** GroupListOut */
        GroupListOut: {
            /** Items */
            items: components["schemas"]["GroupSummaryOut"][];
        };
        /** GroupSummaryOut */
        GroupSummaryOut: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Grouping Basis */
            grouping_basis: string | null;
            /** Grouping Confidence */
            grouping_confidence: number | null;
            /** Is Pinned */
            is_pinned: boolean;
            /** Album */
            album: string | null;
            /** Album Artist */
            album_artist: string | null;
            /** Year */
            year: number | null;
            /** Track Count */
            track_count: number;
            /** Expected Track Count */
            expected_track_count: number | null;
            /** Match State */
            match_state: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportSessionDetailOut */
        ImportSessionDetailOut: {
            /** Id */
            id: number;
            /** Library Root */
            library_root: string;
            /** State */
            state: string;
            /** Job Id */
            job_id: number | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Tasks */
            tasks: components["schemas"]["ImportTaskOut"][];
            /** Changeset Ids */
            changeset_ids: number[];
        };
        /** ImportSessionSummaryOut */
        ImportSessionSummaryOut: {
            /** Id */
            id: number;
            /** Library Root */
            library_root: string;
            /** State */
            state: string;
            /** Job Id */
            job_id: number | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
        };
        /** ImportTaskOut */
        ImportTaskOut: {
            /** Stage */
            stage: string;
            /** Seq */
            seq: number;
            /** State */
            state: string;
            /** Error */
            error: string | null;
        };
        /** InlineSpanOut */
        InlineSpanOut: {
            /**
             * Op
             * @enum {string}
             */
            op: "equal" | "insert" | "delete";
            /** Text */
            text: string;
        };
        /** JobDetailOut */
        JobDetailOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** State */
            state: string;
            /** Priority */
            priority: number;
            /** Progress Current */
            progress_current: number;
            /** Progress Total */
            progress_total: number | null;
            /** Progress Message */
            progress_message: string | null;
            /** Attempts */
            attempts: number;
            /** Error */
            error: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * JobEnqueuedOut
         * @description POST .../apply, .../undo, /api/scan, and /api/imports all return
         *     this — docs/PLAN.md §10: `POST .../apply -> 202 {job_id}`. Poll
         *     GET /api/jobs/{id} or subscribe to GET /api/jobs/{id}/events for
         *     the outcome.
         */
        JobEnqueuedOut: {
            /** Job Id */
            job_id: number;
        };
        /** JobPageOut */
        JobPageOut: {
            /** Items */
            items: components["schemas"]["JobSummaryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** JobSummaryOut */
        JobSummaryOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** State */
            state: string;
            /** Priority */
            priority: number;
            /** Progress Current */
            progress_current: number;
            /** Progress Total */
            progress_total: number | null;
            /** Progress Message */
            progress_message: string | null;
            /** Attempts */
            attempts: number;
            /** Error */
            error: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /** MatchProposalOut */
        MatchProposalOut: {
            /** Candidates */
            candidates: components["schemas"]["CandidateRowOut"][];
            /** Auto Applicable */
            auto_applicable: boolean;
            /** Needs Confirmation */
            needs_confirmation: boolean;
        };
        /** MergeGroupsRequest */
        MergeGroupsRequest: {
            /** From Group Ids */
            from_group_ids: number[];
        };
        /** MultiValueDiffOut */
        MultiValueDiffOut: {
            /** Added */
            added: string[];
            /** Removed */
            removed: string[];
            /** Unchanged */
            unchanged: string[];
        };
        /** PathPreviewOut */
        PathPreviewOut: {
            /** Rows */
            rows: components["schemas"]["PathPreviewRowOut"][];
        };
        /** PathPreviewRequest */
        PathPreviewRequest: {
            /** Track Ids */
            track_ids?: number[] | null;
            /** Group Id */
            group_id?: number | null;
            /** Template */
            template?: string | null;
        };
        /** PathPreviewRowOut */
        PathPreviewRowOut: {
            /** Track Id */
            track_id: number;
            /** Old Path */
            old_path: string;
            /** New Path */
            new_path: string;
            /** Errors */
            errors: string[];
            /** Is Collision */
            is_collision: boolean;
        };
        /** PathRenameRequest */
        PathRenameRequest: {
            /** Track Ids */
            track_ids?: number[] | null;
            /** Group Id */
            group_id?: number | null;
            /** Template */
            template?: string | null;
        };
        /** ReassignTrackRequest */
        ReassignTrackRequest: {
            /** Track Id */
            track_id: number;
            /** To Group Id */
            to_group_id: number;
        };
        /** RunCascadeResultOut */
        RunCascadeResultOut: {
            /** Groups Created */
            groups_created: number;
            /** Groups Updated */
            groups_updated: number;
            /** Tracks Grouped */
            tracks_grouped: number;
            /** Tracks Skipped Pinned */
            tracks_skipped_pinned: number;
        };
        /** ScanRequest */
        ScanRequest: {
            /** Root */
            root: string;
        };
        /** SplitGroupRequest */
        SplitGroupRequest: {
            /** Track Ids */
            track_ids: number[];
        };
        /** StageMatchRequest */
        StageMatchRequest: {
            /** Source */
            source: string;
            /** Ref Id */
            ref_id: string;
        };
        /** StartImportRequest */
        StartImportRequest: {
            /** Library Root */
            library_root: string;
        };
        /** StripRequest */
        StripRequest: {
            /** Track Ids */
            track_ids: number[];
        };
        /** TrackDetailOut */
        TrackDetailOut: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Filename */
            filename: string;
            /** Ext */
            ext: string;
            /** Title */
            title: string | null;
            /** Artist */
            artist: string | null;
            /** Album */
            album: string | null;
            /** Album Artist */
            album_artist: string | null;
            /** Track No */
            track_no: number | null;
            /** Disc No */
            disc_no: number | null;
            /** Year */
            year: number | null;
            /** Genre */
            genre: string[];
            /** Duration Ms */
            duration_ms: number | null;
            /** Format */
            format: string | null;
            /** Bitrate */
            bitrate: number | null;
            /** Has Embedded Art */
            has_embedded_art: boolean;
            /** Has Lyrics */
            has_lyrics: boolean;
            /** Probe Error */
            probe_error: string | null;
            /** Missing Since */
            missing_since: string | null;
            /** Artists */
            artists: string[];
            /** Composer */
            composer: string | null;
            /** Track Total */
            track_total: number | null;
            /** Disc Total */
            disc_total: number | null;
            /** Original Year */
            original_year: number | null;
            /** Date */
            date: string | null;
            /** Compilation */
            compilation: boolean;
            /** Label */
            label: string | null;
            /** Catalog Number */
            catalog_number: string | null;
            /** Barcode */
            barcode: string | null;
            /** Isrc */
            isrc: string | null;
            /** Country */
            country: string | null;
            /** Media */
            media: string | null;
            /** Mood */
            mood: string[];
            /** Bpm */
            bpm: number | null;
            /** Key */
            key: string | null;
            /** Mb Track Id */
            mb_track_id: string | null;
            /** Mb Release Id */
            mb_release_id: string | null;
            /** Mb Recording Id */
            mb_recording_id: string | null;
            /** Mb Artist Id */
            mb_artist_id: string | null;
            /** Discogs Release Id */
            discogs_release_id: string | null;
            /** Deezer Track Id */
            deezer_track_id: string | null;
            /** Acoustid Id */
            acoustid_id: string | null;
            /** Sample Rate */
            sample_rate: number | null;
            /** Channels */
            channels: number | null;
            /** Codec */
            codec: string | null;
            /** Comment */
            comment: string | null;
            /** Encoder */
            encoder: string | null;
            /** Extra Tags */
            extra_tags: {
                [key: string]: string;
            };
            /** Group Id */
            group_id: number | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Scanned At
             * Format: date-time
             */
            last_scanned_at: string;
            /** Lyrics Synced */
            lyrics_synced: boolean;
            /** Rg Track Gain */
            rg_track_gain: number | null;
            /** Rg Album Gain */
            rg_album_gain: number | null;
            /** Art Blob Id */
            art_blob_id: number | null;
        };
        /** TrackPageOut */
        TrackPageOut: {
            /** Items */
            items: components["schemas"]["TrackSummaryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /**
         * TrackPatchRequest
         * @description PATCH /api/tracks/{id} body: canonical field name -> new value.
         *     Creates a DRAFT ChangeSet per docs/PLAN.md §10, never writes
         *     directly.
         */
        TrackPatchRequest: {
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
        };
        /** TrackSummaryOut */
        TrackSummaryOut: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Filename */
            filename: string;
            /** Ext */
            ext: string;
            /** Title */
            title: string | null;
            /** Artist */
            artist: string | null;
            /** Album */
            album: string | null;
            /** Album Artist */
            album_artist: string | null;
            /** Track No */
            track_no: number | null;
            /** Disc No */
            disc_no: number | null;
            /** Year */
            year: number | null;
            /** Genre */
            genre: string[];
            /** Duration Ms */
            duration_ms: number | null;
            /** Format */
            format: string | null;
            /** Bitrate */
            bitrate: number | null;
            /** Has Embedded Art */
            has_embedded_art: boolean;
            /** Has Lyrics */
            has_lyrics: boolean;
            /** Probe Error */
            probe_error: string | null;
            /** Missing Since */
            missing_since: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusOut"];
                };
            };
        };
    };
    status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusOut"];
                };
            };
        };
    };
    list_tracks_api_tracks_get: {
        parameters: {
            query?: {
                q?: string | null;
                sort?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_api_tracks__track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_track_api_tracks__track_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_changesets_api_changesets_get: {
        parameters: {
            query?: {
                state?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_changeset_api_changesets__change_set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                change_set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_changes_api_changesets__change_set_id__changes_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                change_set_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyDecisionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_changeset_api_changesets__change_set_id__apply_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                change_set_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_changeset_api_changesets__change_set_id__undo_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                change_set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_edit_tracks_api_tracks_bulk_edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_find_replace_api_tracks_find_replace_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindReplaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindReplacePreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_find_replace_api_tracks_find_replace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindReplaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strip_tracks_api_tracks_strip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StripRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupListOut"];
                };
            };
        };
    };
    get_group_api_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_cascade_api_groups_cascade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCascadeResultOut"];
                };
            };
        };
    };
    merge_groups_api_groups__group_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeGroupsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_group_api_groups__group_id__split_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reassign_track_api_groups__group_id__reassign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReassignTrackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    force_to_singleton_api_groups_force_singleton_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForceSingletonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pin_group_api_groups__group_id__pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fields_api_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldListOut"];
                };
            };
        };
    };
    get_group_candidates_api_groups__group_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchProposalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stage_group_api_groups__group_id__stage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_candidates_api_tracks__track_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchProposalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stage_track_api_tracks__track_id__stage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_paths_api_paths_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_paths_api_paths_rename_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                state?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_api_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_import_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSessionSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_api_imports__import_session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_import_api_imports__import_session_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSessionSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_replaygain_api_enrich_replaygain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedOut"];
                };
            };
        };
    };
    enrich_art_api_enrich_art_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedOut"];
                };
            };
        };
    };
    enrich_lyrics_api_enrich_lyrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedOut"];
                };
            };
        };
    };
    list_duplicates_api_duplicates_get: {
        parameters: {
            query?: {
                include_dismissed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateGroupListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_duplicate_api_duplicates__group_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_duplicates_api_duplicates_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedOut"];
                };
            };
        };
    };
    get_blob_api_blobs__blob_id__get: {
        parameters: {
            query?: {
                size?: string | null;
            };
            header?: never;
            path: {
                blob_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spa_catch_all__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
